language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - sed '2 a \"homepage\": \"/sync-beat/\",' package.json
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
